# =============================================================================
# Template: proxy-pass
# Generated by new-site.sh — do not edit manually.
# Re-run new-site.sh to regenerate.
#
# Use for: any HTTP upstream running inside the cluster
#   - Node.js / Next.js
#   - Django / Flask / FastAPI / Go / Rust
#   - PHP-FPM with nginx sidecar (sidecar exposes HTTP — transparent here)
#
# Cert is mounted at /etc/nginx/certs/${DOMAIN}/ by the DaemonSet.
# Upstream is resolved via CoreDNS at 10.96.0.10 (resolver in nginx.conf).
# The set $upstream trick forces re-resolution each request cycle —
# pod IPs change on restart and must not be cached at nginx startup.
#
# Variables:
#   DOMAIN        — public domain, e.g. api.yourdomain.com
#   SERVICE_NAME  — Kubernetes Service name
#   NAMESPACE     — Kubernetes namespace
#   SERVICE_PORT  — port the Service exposes
#   SITE_NAME     — slug for log filenames (auto-derived by new-site.sh)
# =============================================================================

server {
    listen 443 ssl;
    server_name ${DOMAIN};

    ssl_certificate     /etc/nginx/certs/${DOMAIN}/tls.crt;
    ssl_certificate_key /etc/nginx/certs/${DOMAIN}/tls.key;

    access_log /var/log/nginx/${SITE_NAME}.access.log main;
    error_log  /var/log/nginx/${SITE_NAME}.error.log warn;

    location / {
        # set $upstream forces CoreDNS re-resolution on every request cycle.
        # A plain proxy_pass "http://name:port" resolves once at config load
        # and caches the IP — breaks silently when pods restart.
        set $upstream ${SERVICE_NAME}.${NAMESPACE}.svc.cluster.local:${SERVICE_PORT};

        proxy_pass         http://$upstream;
        proxy_http_version 1.1;

        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";

        proxy_connect_timeout 10s;
        proxy_read_timeout    60s;
        proxy_send_timeout    60s;

        proxy_buffer_size       16k;
        proxy_buffers           4 32k;
        proxy_busy_buffers_size 64k;
    }
}
