# =============================================================================
# Template: static-files
# Generated by new-site.sh — do not edit manually.
#
# Use for: compiled static output served from the ingress node filesystem.
#   - React / Vue / Svelte / Angular SPA builds
#   - Next.js static export (next export)
#   - Plain HTML/CSS/JS sites
#   - Documentation sites (Docusaurus, VitePress, etc.)
#
# Deployment model (nginx runs on INGRESS_NODE, not VPS):
#   rsync -av --delete ./dist/ adminuser@10.0.0.36:${WEBROOT}/
#
# No upstream — nginx serves files locally from the worker node filesystem.
# No resolver needed.
#
# Cert is mounted at /etc/nginx/certs/${DOMAIN}/ by the DaemonSet.
# Kubernetes mounts Secret keys as files: tls.crt and tls.key.
#
# Variables:
#   DOMAIN    — public domain, e.g. www.yourdomain.com
#   WEBROOT   — absolute path on ingress node, e.g. /var/www/mysite
#   SITE_NAME — slug used in log filenames
# =============================================================================

server {
    listen 443 ssl;
    server_name ${DOMAIN};

    ssl_certificate     /etc/nginx/certs/${DOMAIN}/tls.crt;
    ssl_certificate_key /etc/nginx/certs/${DOMAIN}/tls.key;

    access_log /var/log/nginx/${SITE_NAME}.access.log main;
    error_log  /var/log/nginx/${SITE_NAME}.error.log warn;

    root  ${WEBROOT};
    index index.html;

    # SPA fallback — serve index.html for unknown paths (client-side routing).
    # Replace with try_files $uri $uri/ =404 for non-SPA multi-page sites.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Immutable assets — content-hashed filenames, cache forever.
    location ~* \.(js|css|woff|woff2|ttf|eot)$ {
        expires max;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Images and media — long cache, not immutable.
    location ~* \.(png|jpg|jpeg|gif|ico|svg|webp|mp4|mp3|pdf)$ {
        expires 30d;
        add_header Cache-Control "public";
        access_log off;
    }

    # HTML — never cache. New deploys must be picked up immediately.
    location ~* \.html$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # Block hidden files (.env, .git, etc.)
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
